name: wintercluster
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=2.117
  - blas-devel=3.9.0
  - boltons=23.0.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - colorama=0.4.6
  - conda=23.7.2
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - contourpy=1.1.0
  - cryptography=41.0.3
  - cycler=0.11.0
  - eigen=3.4.0
  - ffmpeg=4.2.2
  - fontconfig=2.13.94
  - fonttools=4.42.0
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.76.4
  - glib-tools=2.76.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - harfbuzz=4.3.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - importlib-resources=6.0.1
  - importlib_resources=6.0.1
  - jpeg=9e
  - jsonpatch=1.32
  - jsonpointer=2.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=12.0.0
  - libcxx=16.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.3.0
  - libglib=2.76.4
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm12=12.0.1
  - libopenblas=0.3.23
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.15
  - libsqlite=3.42.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.7.3
  - nspr=4.35
  - nss=3.89
  - numpy=1.25.2
  - openblas=0.3.23
  - opencv=4.6.0
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.1.2
  - packaging=23.1
  - pcre2=10.40
  - pillow=9.4.0
  - pip=23.2.1
  - pixman=0.38.0
  - pluggy=1.2.0
  - pthread-stubs=0.4
  - pycosat=0.6.4
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python_abi=3.9
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.31.0
  - ruamel.yaml=0.17.32
  - ruamel.yaml.clib=0.2.7
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.42.0
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.3.2
  - tqdm=4.65.0
  - tzdata=2023c
  - unicodedata2=15.0.0
  - urllib3=2.0.4
  - wheel=0.41.1
  - x264=1!157.20191217
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.2
  - zipp=3.16.2
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - pathlib2==2.3.7.post1
      - runsnakerun==2.0.5
      - snakeviz==2.2.0
      - squaremap==1.0.5
      - wxpython==4.2.1